using System.Text;
using MonitorCloud.Infrastructure.Licensing.Fake;

namespace MonitorCloud.Infrastructure.Seeding;

/// <summary>
/// Deterministic Licensing data of the demo customers (08 sections 2 and 5): plans, one customer, subscription and
/// licence per tenant, product keys, and the fingerprints of the licensed devices (shared with the device seed).
/// </summary>
internal static class DemoLicensing
{
    private const string KeyAlphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

    public static readonly (string Code, string Name, int Limit, string[] Features, decimal Price)[] Plans =
    [
        ("STARTER", "Starter", 50, ["monitoring", "alerts", "reports.basic"], 49),
        ("PROFESSIONAL", "Professional", 200, ["monitoring", "alerts", "reports.basic", "notifications.email", "monitorpoints"], 149),
        ("BUSINESS", "Business", 250, ["monitoring", "alerts", "reports.basic", "notifications.email", "monitorpoints", "reports.advanced", "archive"], 249),
        ("ENTERPRISE", "Enterprise", 500, ["monitoring", "alerts", "reports.basic", "notifications.email", "monitorpoints", "reports.advanced", "archive", "notifications.webhook", "remote.actions"], 499),
    ];

    /// <summary>The agent fingerprint of the n-th device of a customer (1-based).</summary>
    public static string Fingerprint(string tenantCode, int index) => $"{tenantCode.ToLowerInvariant()}-dev-{index:0000}";

    public static Guid NewGuid(Random random)
    {
        var bytes = new byte[16];
        random.NextBytes(bytes);
        bytes[7] = (byte)((bytes[7] & 0x0F) | 0x40);
        bytes[8] = (byte)((bytes[8] & 0x3F) | 0x80);
        return new Guid(bytes);
    }

    public static string ProductKey(Random random)
    {
        var builder = new StringBuilder();
        for (var group = 0; group < 5; group++)
        {
            if (group > 0)
                builder.Append('-');
            for (var i = 0; i < 6; i++)
                builder.Append(KeyAlphabet[random.Next(KeyAlphabet.Length)]);
        }

        return builder.ToString();
    }

    public static FakeLicensingData NewData(Random random) => new()
    {
        ProductCode = "000001",
        Plans = [.. Plans.Select(p => new FakePlan
        {
            Id = NewGuid(random), Code = p.Code, Name = p.Name, Version = 1, Features = [.. p.Features], MaxActivations = p.Limit, DurationDays = 365, Price = p.Price, Currency = "USD",
        })],
    };

    public static void AddCustomer(FakeLicensingData data, Random random, Guid customerId, string name, string code, string? country, string plan,
        bool suspended, DateTimeOffset since, DateTimeOffset renews, int licensedDevices)
    {
        var subscriptionId = NewGuid(random);
        data.Customers.Add(new FakeCustomer { Id = customerId, Name = name, Email = $"billing@{code.ToLowerInvariant()}.test", Country = country, Status = "Active", CreatedAt = since });
        data.Subscriptions.Add(new FakeSubscription { Id = subscriptionId, CustomerId = customerId, PlanCode = plan, Status = suspended ? "Suspended" : "Active", StartDate = since, EndDate = renews });
        data.Licenses.Add(new FakeLicense
        {
            Id = NewGuid(random),
            CustomerId = customerId,
            SubscriptionId = subscriptionId,
            LicenseNumber = $"LIC-{code}-0001",
            ProductKey = ProductKey(random),
            Status = "Active",
            ExpiresAt = renews,
            MaxActivations = Plans.First(p => p.Code == plan).Limit,
            Devices = [.. Enumerable.Range(1, licensedDevices).Select(i => Fingerprint(code, i))],
        });
    }

    public static string Readme(FakeLicensingData data, IReadOnlyDictionary<Guid, (string Name, string Code)> customers)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Demo seed files");
        builder.AppendLine();
        builder.AppendLine("Generated by `DemoSeeder` (08-seed-data.md). Do not edit by hand: run");
        builder.AppendLine("`dotnet run --project src/MonitorCloud.Api -- seed --reset` to regenerate.");
        builder.AppendLine();
        builder.AppendLine("- `licensing-fake.json` - the data of `FakeLicensingGateway` (`Licensing:Mode = Fake`).");
        builder.AppendLine("- `*.local.json` - git-ignored (live credentials written by `tools/MonitorCloud.LicensingSeeder`).");
        builder.AppendLine();
        builder.AppendLine("## Demo product keys (fake mode only)");
        builder.AppendLine();
        builder.AppendLine("| Customer | Code | Plan | Product key |");
        builder.AppendLine("|---|---|---|---|");
        foreach (var license in data.Licenses)
        {
            var (name, code) = customers[license.CustomerId];
            var plan = data.Subscriptions.First(s => s.Id == license.SubscriptionId).PlanCode;
            builder.AppendLine($"| {name} | {code} | {plan} | `{license.ProductKey}` |");
        }

        return builder.ToString();
    }
}
