using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using MonitorCloud.Application.Abstractions.Context;
using MonitorCloud.Application.Abstractions.Storage;
using MonitorCloud.Application.Reports;
using MonitorCloud.Domain.Archive;
using MonitorCloud.Domain.Devices;
using MonitorCloud.Domain.Identity;
using MonitorCloud.Domain.Media;
using MonitorCloud.Domain.Reports;
using MonitorCloud.Domain.Tenancy;
using MonitorCloud.Infrastructure.Persistence;

namespace MonitorCloud.Infrastructure.Seeding;

/// <summary>
/// Part 5 of the demo seed (MC-906, 08 section 4): four finished Acme reports generated by the real report job (small real
/// CSV files), and the Acme archive: company profile, 3 contacts, 4 files, 2 notes (1 internal), 2 remote-access entries.
/// </summary>
internal sealed class DemoArchive(AppDbContext db, IMediaStorage storage, ISecretProtector protector, ReportGenerationService reports, ITenantScopeSetter scope, DateTimeOffset now)
{
    /// <summary>The demo remote-access password (development only, like the demo user passwords).</summary>
    public const string RemotePassword = "DEV-ONLY-remote-Acme1";

    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

    public async Task RunAsync(CancellationToken ct)
    {
        var acme = await db.Set<Tenant>().SingleAsync(t => t.Code == "ACME", ct);
        var admin = await db.Set<User>().IgnoreQueryFilters().SingleAsync(u => u.Email == "admin@acme.test", ct);
        var support = await db.Set<User>().IgnoreQueryFilters().SingleAsync(u => u.Email == "support@monitor.local", ct);
        var cairo = await db.Set<Location>().IgnoreQueryFilters().SingleAsync(l => l.TenantId == acme.Id && l.Code == "CAIRO-HQ", ct);
        var desk = await db.Set<Device>().IgnoreQueryFilters().FirstAsync(d => d.TenantId == acme.Id && d.Name == "DESK-01", ct);
        var fileServer = await db.Set<Device>().IgnoreQueryFilters().FirstAsync(d => d.TenantId == acme.Id && d.Name == "FILE-SRV-01", ct);

        var profile = CustomerProfile.Create(acme.Id, now);
        profile.Update("Logistics", "https://acme.test", "+20 2 0000 0100", "1 Sample Street, Cairo", "Support User", now);
        db.AddRange(
            profile,
            ArchiveContact.Create(acme.Id, "Nadia Sample", "nadia@acme.test", "+20 100 000 0001", "IT Director", true),
            ArchiveContact.Create(acme.Id, "Omar Example", "omar@acme.test", "+20 100 000 0002", "Network Engineer", false),
            ArchiveContact.Create(acme.Id, "Laila Placeholder", "laila@acme.test", null, "Finance Manager", false),
            ArchiveNote.Create(acme.Id, "Kick-off call done. Cairo HQ and Alexandria branch are monitored first; the other sites follow next quarter.", false,
                admin.Id, admin.FullName, now.AddDays(-20)),
            ArchiveNote.Create(acme.Id, "Renewal discussion planned for next month. The customer asked about the Enterprise remote actions.", true,
                support.Id, support.FullName, now.AddDays(-3)),
            RemoteAccessEntry.Create(acme.Id, cairo.Id, desk.Id, "AnyDesk", "Front desk PC", protector.Protect("123 456 789"), protector.Protect(RemotePassword), now.AddDays(-15)),
            RemoteAccessEntry.Create(acme.Id, cairo.Id, fileServer.Id, "RDP", "File server", protector.Protect("192.168.1.80:3389"), protector.Protect(RemotePassword), now.AddDays(-15)));

        var files = new (string Name, string Display, byte[] Bytes, int DaysAgo)[]
        {
            ("service-agreement.pdf", "Service Agreement 2026", MinimalPdf("Service Agreement - Acme Corporation (demo)"), 60),
            ("network-diagram.png", "Cairo HQ network diagram", MinimalPng(), 45),
            ("onboarding-checklist.txt", "Onboarding checklist", Encoding.UTF8.GetBytes("1. Install the agent on the servers\n2. Add monitor points\n3. Invite the IT team\n"), 30),
            ("asset-register.csv", "Asset register", Encoding.UTF8.GetBytes("Device,Location,Owner\nWEB-SRV-01,Cairo HQ,IT\nFILE-SRV-01,Cairo HQ,IT\nDESK-01,Cairo HQ,Reception\n"), 10),
        };
        foreach (var (name, display, bytes, daysAgo) in files)
        {
            var media = MediaFile.Create(acme.Id, name, bytes.Length, Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(), now.AddDays(-daysAgo));
            await storage.WriteAsync(media.StoragePath, bytes, ct);
            db.AddRange(media, ArchiveFile.Create(acme.Id, media.Id, display, bytes.Length, admin.Id, false, now.AddDays(-daysAgo)));
        }

        // Four reports through the real generation job, so the files hold the seeded numbers.
        var requests = new (string Type, int DaysAgo, int Days)[] { ("overview", 1, 7), ("device-health", 2, 7), ("alerts", 7, 30), ("license-usage", 14, 30) };
        foreach (var (type, daysAgo, days) in requests)
        {
            var at = now.AddDays(-daysAgo);
            var parameters = new ReportParameters([], [], at.AddDays(-days), at, "device");
            var definition = ReportCatalog.Find(type)!;
            db.Add(GeneratedReport.Request(acme.Id, type, $"{definition.Title} {parameters.From.UtcDateTime:yyyy-MM-dd} - {parameters.To.UtcDateTime:yyyy-MM-dd}",
                JsonSerializer.Serialize(parameters, Json), ReportFormat.Csv, admin.Id, at));
        }

        await db.SaveChangesAsync(ct);
        try
        {
            while (await reports.RunOneAsync(ct))
            {
            }
        }
        finally
        {
            scope.RunAsSystem();
        }
    }

    /// <summary>A one-page PDF with a line of text (valid enough for every viewer).</summary>
    private static byte[] MinimalPdf(string text)
    {
        var stream = $"BT /F1 14 Tf 72 720 Td ({text}) Tj ET";
        var objects = new[]
        {
            "<< /Type /Catalog /Pages 2 0 R >>",
            "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
            $"<< /Length {stream.Length} >>\nstream\n{stream}\nendstream",
            "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        };
        var pdf = new StringBuilder("%PDF-1.4\n");
        var offsets = new List<int>();
        for (var i = 0; i < objects.Length; i++)
        {
            offsets.Add(pdf.Length);
            pdf.Append(i + 1).Append(" 0 obj\n").Append(objects[i]).Append("\nendobj\n");
        }

        var xref = pdf.Length;
        pdf.Append("xref\n0 ").Append(objects.Length + 1).Append("\n0000000000 65535 f \n");
        foreach (var offset in offsets)
            pdf.Append(offset.ToString("D10", System.Globalization.CultureInfo.InvariantCulture)).Append(" 00000 n \n");
        pdf.Append("trailer\n<< /Size ").Append(objects.Length + 1).Append(" /Root 1 0 R >>\nstartxref\n").Append(xref).Append("\n%%EOF\n");
        return Encoding.ASCII.GetBytes(pdf.ToString());
    }

    /// <summary>A 1x1 green PNG.</summary>
    private static byte[] MinimalPng() => Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4z8DwHwAFAAH/q842iQAAAABJRU5ErkJggg==");
}
