using MonitorCloud.SharedKernel;

namespace MonitorCloud.Domain.Reports;

public enum ReportStatus
{
    Queued,
    Running,
    Done,
    Failed,
}

public enum ReportFormat
{
    Csv,
    Pdf,
}

/// <summary>A report request and its result (02 section 9). Generated by the background job.</summary>
public sealed class GeneratedReport : Entity, ITenantOwned
{
    public static readonly IReadOnlyList<string> Types = ["overview", "location-summary", "device-health", "performance", "network-usage", "alerts", "license-usage", "custom"];

    private GeneratedReport()
    {
        Type = string.Empty;
        Title = string.Empty;
        ParametersJson = "{}";
    }

    public Guid TenantId { get; private set; }
    public string Type { get; private set; }
    public string Title { get; private set; }
    public string ParametersJson { get; private set; }
    public ReportFormat Format { get; private set; }
    public ReportStatus Status { get; private set; }
    public Guid? MediaId { get; private set; }
    public long SizeBytes { get; private set; }
    public Guid RequestedByUserId { get; private set; }
    public DateTimeOffset RequestedAt { get; private set; }
    public DateTimeOffset? CompletedAt { get; private set; }
    public string? Error { get; private set; }

    public static GeneratedReport Request(Guid tenantId, string type, string title, string parametersJson, ReportFormat format, Guid userId, DateTimeOffset now)
    {
        Guard.Against(!Types.Contains(type), SharedKernel.Error.Validation(Guard.ValidationCode, "Unknown report type."));
        return new GeneratedReport
        {
            TenantId = Guard.NotEmpty(tenantId, nameof(TenantId)),
            Type = type,
            Title = Guard.NotEmpty(title, nameof(Title), 200),
            ParametersJson = Guard.NotEmpty(parametersJson, nameof(ParametersJson), 8000),
            Format = format,
            Status = ReportStatus.Queued,
            RequestedByUserId = userId,
            RequestedAt = now,
        };
    }

    public void Start() => Status = ReportStatus.Running;

    public void Complete(Guid mediaId, long sizeBytes, DateTimeOffset now)
    {
        Status = ReportStatus.Done;
        MediaId = mediaId;
        SizeBytes = sizeBytes;
        CompletedAt = now;
        Error = null;
    }

    public void Fail(string error, DateTimeOffset now)
    {
        Status = ReportStatus.Failed;
        Error = error.Length <= 500 ? error : error[..500];
        CompletedAt = now;
    }
}
